[package]
name = "imageflow_core"
version = "0.1.0"
authors = ["Lilith River <lilith@imazen.io>"]
workspace = "../"
edition = "2021"

[lib]
name = "imageflow_core"
doctest = false
bench = false

[dependencies]
libc = "0.2"
num = "0.4"
time = "0.3" #
chrono =  "0.4"
serde = "1"
serde_json = "1"
serde_derive = "1"
lazy_static = "1"
twox-hash = "2"
fnv = "1"
blake2-rfc = "0.2"

## Crate-specific dependencies
threadpool = "1"
petgraph = "0.6" #Upgrade to
daggy = "0.8" # Upgrade to

smallvec = "1"
itertools = "0.14"
imgref = "1.4.1"
slotmap = "1"
base64 = "0.22"
hex = "0.4"
gif = "0.13.1"
rgb = { version = "0.8", features = ["argb"] }
imagequant = "4"
lodepng = "3"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
libwebp-sys = { version = "0.12", features = ["neon"] }
libz-sys = { version="1", features = ["static"] }
zune-bmp = "0.5.0-rc4"

bytemuck = "1"

jpeg-decoder ="0.3.1"

lcms2 = "6"
lcms2-sys = "4"
chashmap = "2.2"

getopts ="0.2"
byteorder="1"

url = "2"
uuid = { version = "1", features = ["v4"] }

rustface = { git = "https://github.com/atomashpolskiy/rustface" }
imageflow_types = { path = "../imageflow_types", version = "*" }
imageflow_helpers = { path = "../imageflow_helpers", version = "*" }
imageflow_riapi = { path = "../imageflow_riapi", version = "*" }
imageflow_c_components = { path = "../c_components" }
mozjpeg = "0.10"
multiversion = "0.8"

mozjpeg-sys = {version = "2", features = ["nasm_simd"]}

evalchroma = "1"




# For build info see https://github.com/kornelski/rust-libpng-sys/blob/master/Cargo.toml
# And https://github.com/kornelski/rust-libpng-sys/blob/master/build.rs
libpng-sys = { version = "1.1.9", features = ["static", "static-libz", "libz-sys"] }


mimalloc = { version = "*", features = ["secure"], optional = true }

[dev-dependencies]
hyper = "1.4"
imageflow_http_helpers = { path = "../imageflow_http_helpers", version = "*" }
dssim = "3.3"
criterion = "0.5"
rand = "*"

[features]
default = []
nightly = []
c_rendering = []
mimalloc = ["dep:mimalloc"]

[[bench]]
name="bench_graphics"
path = "benches/bench_graphics.rs"
harness = false


