[package]
name = "imageflow_core"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
build = "conan_cargo_build.rs"
links = "imageflow_c"
workspace = "../"

[lib]
name = "imageflow_core"
doctest = false

[dependencies]
libc = "0.2"

num = "0.1"

# time
time = "0.1"
chrono =  "0.4"

# serialization
serde = "1"
serde_json = "1"
serde_derive = "1"
rustc-serialize = "0.3"

#lazy static
lazy_static = "0.2"

# fast hashes, crypto hashs
twox-hash = "1"
fnv = "*"
blake2-rfc = "0.2"

## Crate-specific dependencies

clap = "2"
threadpool = "1"
petgraph = "0.4"
daggy = "0.5"

smallvec = "*"

gif = "*"
rgb = "0.8.5"
imagequant = "2.11.7"
lodepng = "2.0.5"

lcms2 = "5.0"
lcms2-sys = {version="*", default-features = false}
chashmap = "2.2"

dssim = "2"
getopts ="0.2.15"

url = "1.4"
uuid = { version = "0.5", features = ["v4"] }

imageflow_types = { path = "../imageflow_types", version = "*" }
imageflow_helpers = { path = "../imageflow_helpers", version = "*" }
imageflow_riapi = { path = "../imageflow_riapi", version = "*" }


[dev-dependencies]
hyper = "=0.10.12"


[build-dependencies]
cmake = "0.1.17"


#cp ../../../cargo/target/x86_64-unknown-linux-gnu/release/cargo /home/n/.cargo/bin/
