[package]
name = "imageflow_core"
version = "0.1.0"
authors = ["Lilith River <lilith@imazen.io>"]
workspace = "../"

[lib]
name = "imageflow_core"
doctest = false

[dependencies]
libc = "0.2"

num = "0.2"

# time
time = "0.1"
chrono =  "0.4"

# serialization
serde = "1"
serde_json = "1"
serde_derive = "1"
rustc-serialize = "0.3"

#lazy static
lazy_static = "1"

# fast hashes, crypto hashes
twox-hash = "1"
fnv = "*"
blake2-rfc = "0.2"

## Crate-specific dependencies

clap = "2"
threadpool = "1"
petgraph = "0.4"
daggy = "0.5" # Upgrade to 0.6

smallvec = "*"

itertools = "*"
imgref = "1.4.0" # upgrade to 1.3.5

dssim = "2.9.7"
gif = "*"
rgb = "0.8.6"
imagequant = "2.11.7"
lodepng = "2.1.2"

lcms2 = "5.1.4"
chashmap = "2.2"

getopts ="0.2"

url = "2"
uuid = { version = "0.7", features = ["v4"] }

rustface = { git = "https://github.com/atomashpolskiy/rustface" }
imageflow_types = { path = "../imageflow_types", version = "*" }
imageflow_helpers = { path = "../imageflow_helpers", version = "*" }
imageflow_riapi = { path = "../imageflow_riapi", version = "*" }
imageflow_c_components = { path = "../c_components" }
mozjpeg = "0.8.5" # upgrade to 0.8.14
evalchroma = "0.1.1"

[dev-dependencies]
hyper = "0.12"

[features]
nightly = ["imageflow_helpers/nightly"]
